"""Playwright Python script generator from .rec files."""

from recordation.models import Recording, StepModel


class PlaywrightExporter:
    """Exports a Recordation .rec model to standalone Python Playwright code."""

    @staticmethod
    def _get_playwright_selector(step: StepModel) -> str:
        """Determines best Playwright locator expression."""
        if not step.target:
            return ""

        selectors = step.target.selectors
        if selectors.testId:
            return f"page.get_by_test_id('{selectors.testId}')"
        if step.target.text and len(step.target.text) < 30 and step.target.tag in ("BUTTON", "A"):
            escaped_text = step.target.text.replace("'", "\\'")
            return f"page.get_by_text('{escaped_text}', exact=False)"
        if selectors.id and not selectors.id.isdigit():
            return f"page.locator('#{selectors.id}')"
        if selectors.name:
            return f"page.locator('[name=\"{selectors.name}\"]')"
        if selectors.ariaLabel:
            return f"page.get_by_label('{selectors.ariaLabel}')"

        escaped_css = selectors.css.replace("'", "\\'")
        return f"page.locator('{escaped_css}')"

    @classmethod
    def export(
        cls,
        recording: Recording,
        is_async: bool = False,
        headless: bool = False,
        slow_mo: int = 100,
        emulate_mobile: bool = True
    ) -> str:
        """Generates runnable Python script."""
        meta = recording.metadata
        viewport = meta.viewport

        code_lines = [
            '#!/usr/bin/env python3',
            '"""',
            f'Generated by Recordation - Visual Automation Builder',
            f'Flow Title: {meta.title}',
            f'Created At: {meta.createdAt}',
            f'Target Device: {meta.device or "Mobile"}',
            '"""',
            '',
            'import sys',
            'import time'
        ]

        if is_async:
            code_lines.extend([
                'import asyncio',
                'from playwright.async_api import async_playwright',
                '',
                'async def run_automation():',
                '    print("Starting Playwright automation...")',
                '    async with async_playwright() as p:',
                f'        browser = await p.chromium.launch(headless={headless}, slow_mo={slow_mo})',
            ])
            indent = '        '
            await_kw = 'await '
        else:
            code_lines.extend([
                'from playwright.sync_api import sync_playwright',
                '',
                'def run_automation():',
                '    print("Starting Playwright automation...")',
                '    with sync_playwright() as p:',
                f'        browser = p.chromium.launch(headless={headless}, slow_mo={slow_mo})',
            ])
            indent = '        '
            await_kw = ''

        # Context setup with viewport and user agent
        user_agent_str = f", user_agent='{meta.userAgent}'" if meta.userAgent else ""
        has_touch = ", has_touch=True" if emulate_mobile else ""
        code_lines.append(
            f"{indent}context = {await_kw}browser.new_context("
            f"viewport={{'width': {viewport.width}, 'height': {viewport.height}}}"
            f"{has_touch}{user_agent_str})"
        )
        code_lines.append(f"{indent}page = {await_kw}context.new_page()")
        code_lines.append(f"{indent}page.set_default_timeout(10000)")
        code_lines.append('')

        # Steps loop
        for i, step in enumerate(recording.steps, start=1):
            desc = step.description or f"Step {i}: {step.type}"
            code_lines.append(f"{indent}# [{i}/{len(recording.steps)}] {desc}")

            # Optional delay between actions
            if step.delayMs and step.delayMs > 200:
                delay_sec = round(step.delayMs / 1000.0, 2)
                if is_async:
                    code_lines.append(f"{indent}await asyncio.sleep({delay_sec})")
                else:
                    code_lines.append(f"{indent}time.sleep({delay_sec})")

            if step.type == "navigate" and step.url:
                code_lines.append(f"{indent}{await_kw}page.goto('{step.url}', wait_until='domcontentloaded')")

            elif step.type == "click":
                loc = cls._get_playwright_selector(step)
                code_lines.append(f"{indent}try:")
                code_lines.append(f"{indent}    {await_kw}{loc}.click()")
                code_lines.append(f"{indent}except Exception as e:")
                # Fallback to xpath or coordinates if locator fails
                if step.target and step.target.selectors.xpath:
                    xp = step.target.selectors.xpath.replace("'", "\\'")
                    code_lines.append(f"{indent}    print(f'Fallback to XPath for step {i}')")
                    code_lines.append(f"{indent}    {await_kw}page.locator('xpath={xp}').click()")
                else:
                    code_lines.append(f"{indent}    print(f'Failed click step {i}: {{e}}')")

            elif step.type == "dblclick":
                loc = cls._get_playwright_selector(step)
                code_lines.append(f"{indent}{await_kw}{loc}.dblclick()")

            elif step.type == "input":
                loc = cls._get_playwright_selector(step)
                val = str(step.value or "").replace("'", "\\'")
                code_lines.append(f"{indent}{await_kw}{loc}.fill('{val}')")

            elif step.type == "select":
                loc = cls._get_playwright_selector(step)
                val = str(step.value or "").replace("'", "\\'")
                code_lines.append(f"{indent}{await_kw}{loc}.select_option(value='{val}')")

            elif step.type == "change":
                loc = cls._get_playwright_selector(step)
                if isinstance(step.value, bool):
                    action = "check()" if step.value else "uncheck()"
                    code_lines.append(f"{indent}{await_kw}{loc}.{action}")
                else:
                    val = str(step.value or "").replace("'", "\\'")
                    code_lines.append(f"{indent}{await_kw}{loc}.fill('{val}')")

            elif step.type == "keydown":
                key = step.key or "Enter"
                code_lines.append(f"{indent}{await_kw}page.keyboard.press('{key}')")

            elif step.type == "submit":
                loc = cls._get_playwright_selector(step)
                code_lines.append(f"{indent}{await_kw}{loc}.press('Enter')")

            elif step.type == "scroll" and step.scroll:
                code_lines.append(f"{indent}{await_kw}page.evaluate('window.scrollTo({step.scroll.x}, {step.scroll.y})')")

            elif step.type == "wait":
                wait_sec = round((step.delayMs or 1000) / 1000.0, 2)
                if is_async:
                    code_lines.append(f"{indent}await asyncio.sleep({wait_sec})")
                else:
                    code_lines.append(f"{indent}time.sleep({wait_sec})")

            code_lines.append('')

        # Close browser and finish
        code_lines.append(f"{indent}print('Automation finished successfully!')")
        code_lines.append(f"{indent}{await_kw}context.close()")
        code_lines.append(f"{indent}{await_kw}browser.close()")
        code_lines.append('')

        if is_async:
            code_lines.append('if __name__ == "__main__":')
            code_lines.append('    asyncio.run(run_automation())')
        else:
            code_lines.append('if __name__ == "__main__":')
            code_lines.append('    run_automation()')

        return '\n'.join(code_lines) + '\n'
